# 정리

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder= LabelEncoder()
from sklearn.linear_model import LogisticRegression
lr_clf.fit(X_train, y_train)
lr_pred=lr_clf.predict(X_test)
lr_pred_proba=lr_clf.predict_proba(X_test)[:,1]
from sklearn.metrics import roc_auc_score, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

def get_clf_eval(y_test, pred=None, pred_proba=None):
    confusion = confusion_matrix( y_test, pred)
    accuracy = accuracy_score(y_test , pred)
    precision = precision_score(y_test , pred)
    recall = recall_score(y_test , pred)
    f1 = f1_score(y_test,pred)
    # ROC-AUC 추가 
    roc_auc = roc_auc_score(y_test, pred_proba)
    print('오차 행렬')
    print(confusion)
    # ROC-AUC print 추가
    print('정확도: {0:.4f}, 정밀도: {1:.4f}, 재현율: {2:.4f},\
    F1: {3:.4f}, AUC:{4:.4f}'.format(accuracy, precision, recall, f1, roc_auc)) 
    
    from lightgbm import LGBMClassifier
    lgbm_clf= LGBMClassifier(n_estimators=1000, num_leaves=64, n_jobs=-1, boost_from_average=False)
lgbm_clf.fit(X_train, y_train)
preds=lgbm_clf.predict(X_test)
preds_proba=lgbm_clf.predict_proba(X_test)[:,1]
card= pd.read_csv('creditcard.csv')
card.drop('Time', axis=1, inplace=True)
card['Amount']=np.log1p(card['Amount']) # 로그를 사용하는 이유? 숫자가 너무 커서 사용
card
features=X=card.iloc[:, :-1]
labels=y=card.iloc[:,-1]
X_train, X_test,y_train, y_test=train_test_split(features, labels, test_size=.3, stratify=labels)
outlier=fraud['V14'][(fraud['V14']>=upper) |(fraud['V14']<=lower)]
outlier.index
# Smote로 오버샘플링 
from imblearn.over_sampling import SMOTE
smote=SMOTE(random_state=0)
X_train_over, y_train_over =smote.fit_resample(X_train, y_train)
pred = np.array([knn_pred, rf_pred, dt_pred, ada_pred]) 
pred = pred.T
print(pred.shape) 
# 앞에 예측치들에대해 새로운 large X를 만듬

# 최종 Stacking 모델을 위한 Classifier생성. 
lr_final = LogisticRegression(C=10) 
lr_final.fit(pred, y_test)
final = lr_final.predict(pred) 

accuracy_score(y_test, final)

In [1]:
## 복습문제

In [2]:
LightGBM의 한가지 단점으로 알려진 것은 적은 데이터 세트에 적용할 경우 과적합이 발생하기 쉽다. 
XGBoost보다LightGBM에 비해 과적합이 될 확률이 적다. 
validation set를 만드는 이유는 ?
-학습을 조기 중단하기 위하여 , 과적합을 피하기위해 
KFold도 3개는 벨류데이션 세트 나머지는 testset이다.


HyperOpt를 사용할때 다음순서 
범위설절 - fmin으로 x, y값 찾기 - 함수 설정 

랜덤포레스트의 설명으로 옳지 않은 것은?
가지를 나눌떄 p개의 변수중 랜덤하게 m개의 변수만 고려한다. sprt(p)개만 
소수의 변수들에 대한 상관성이나 원소가 가진 영향력을 제거할 수 있다. 
원본 데이터 건수가 200개일때 10개의 결정트리기반으로 학습하려고 하면 20개씩 10개의 데이터건수로 나눈다.X
여러개의 데이터 세트를 분할 할 떄 부트스트래핑 분할 방식을 이용하며, 이는 중첩 복권을 허용한다.

X_train, X_test y_train y test
X_tr X-val y_tr y_var 은 총 6개로 나뉨 


from hyperopt import hp 
search_space={'x':hp.quniform(20 ,20, 2)}

LightGBM은 학습시간이 더 빠르고 더 적은 메모리를 사용한다.

LightGBM은 균형잡힌 트리 유지 x 깊이가 더 깊어짐 

HyperOpt 적용하여  최적으 파라미터 값 찾을 때 교차검증 정확도의 평균에 -1을 곱하여 목적함수 입력값 fmin
로 넣는 이유는 무엇인가?
hyperopt는 최소일수록 좋은데 최대일수록 좋은 값을 표현하려고 
hyperopt는 목적함스 반환 값이 최대값을 가지는 최적 입력값을 유추한다.(O/X)= X 
max_depth의 default 값은 ? default= -1트리의 깊이에 제한이 없다. 

싸이킷런 분류 알고리즘에서 각 label데이터의 확률 보여주는 메소드는?
Roc곡선중에서 직선에 가까울 수록 성능 떨어짐 
분류 결정 임곗값이 높아질수록 Positive로 예측할 확률이 높아진다. x

오차행렬 원소값 이용하여 정밀도, 재현율, 특이도 수식
정밀도 TP/(TP+FP) 
재현율 TP/(TP+FN)
특이도 TN/(TN+FP)/ FPR = 1-특이도

SyntaxError: invalid syntax (3541513997.py, line 1)

In [3]:
import pydataset

In [21]:
mpg= pydataset.data('mpg')

In [18]:
mpg

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
1,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
2,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
3,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
4,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
5,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
...,...,...,...,...,...,...,...,...,...,...,...
230,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize
231,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize
232,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize
233,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize
234,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize

In [6]:
from collections import Counter

In [7]:
Counter(mpg.fl)

Counter({'p': 52, 'r': 168, 'e': 8, 'd': 5, 'c': 1})

In [25]:
mpg.drop([mpg.f1=='c',mpg.f1=='d',mpg.f1=='e'], axis=0)

AttributeError: 'DataFrame' object has no attribute 'f1'

In [10]:
mpg['fl'].pop(['c','d','e'])

KeyError: "None of [Index(['c', 'd', 'e'], dtype='object')] are in the [index]"

In [12]:
import numpy as np
mpg['fl'].replace(['e', 'd', 'c'], np.nan, inplace = True)
mpg['fl'].dropna()

1      p
2      p
3      p
4      p
5      p
      ..
230    p
231    p
232    p
233    p
234    p
Name: fl, Length: 220, dtype: object

In [14]:
data = pd.DataFrame(Counter(mpg.fl),index = [1]).T[:2]
data

NameError: name 'pd' is not defined

In [24]:
mpg=mpg.loc[(mpg.fl == 'p') | (mpg.fl == 'r')] 
mpg

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
1,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
2,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
3,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
4,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
5,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
...,...,...,...,...,...,...,...,...,...,...,...
230,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize
231,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize
232,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize
233,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize
234,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize

In [16]:
a = mpg[mpg['fl']=='p']
b = mpg[mpg['fl']=='r']
import pandas as pd
pd.concat([a,b])

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
1,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
2,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
3,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
4,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
5,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
...,...,...,...,...,...,...,...,...,...,...,...
221,volkswagen,jetta,2.8,1999,6,manual(m5),f,17,24,r,compact
224,volkswagen,new beetle,2.0,1999,4,manual(m5),f,21,29,r,subcompact
225,volkswagen,new beetle,2.0,1999,4,auto(l4),f,19,26,r,subcompact
226,volkswagen,new beetle,2.5,2008,5,manual(m5),f,20,28,r,subcompact
227,volkswagen,new beetle,2.5,2008,5,auto(s6),f,20,29,r,subcompact

In [23]:
mpg.query("fl == 'p' | fl == 'r'")

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
1,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
2,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
3,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
4,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
5,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
...,...,...,...,...,...,...,...,...,...,...,...
230,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize
231,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize
232,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize
233,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize
234,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize

In [ ]:
mpg = mpg[mpg.fl!='e']
mpg = mpg[mpg.fl!='d']
mpg = mpg[mpg.fl!='c']

In [32]:
features= mpg.drop('fl', axis=1)
labels= mpg[['fl']]

In [45]:
features =X =  mpg[['manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty',
       'hwy', 'class']]
labels = y=mpg['fl']

In [ ]:
Q3.
현재 피쳐값에 문자열이 존재한다. 
이를 레이블 인코딩하시오.

In [34]:
from sklearn.preprocessing import LabelEncoder

In [35]:
encoder= LabelEncoder()

In [42]:
labels=np.array(labels).reshape(-1,1)
labels

array([['p'],
       ['p'],
       ['p'],
       ['p'],
       ['p'],
       ['p'],
       ['p'],
       ['p'],
       ['p'],
       ['p'],
       ['p'],
       ['p'],
       ['p'],
       ['p'],
       ['p'],
       ['p'],
       ['p'],
       ['p'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['p'],
       ['p'],
       ['p'],
       ['p'],
       ['p'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['p'],
       ['r'],
       ['r'],
       ['r'],
       ['p'],
       ['r'],
       ['r'],
       ['r'],
       ['p'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['p'],
       ['p'],
       ['r'],
       ['r'],
       ['p'],
       ['r'],
       ['p'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['p'],
       ['p'],
       ['r'],
       ['r'],
       ['p'],
       ['r'],
       ['r'],
       ['p'],
       ['p'],
       ['r'],
       ['p'],
       ['r'],
       ['r'],
       ['p'],
       ['r'],
       ['r'],
       ['r'],
       ['p'],
       ['r'],
       ['p'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['p'],
       ['r'],
       ['p'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['p'],
       ['p'],
       ['r'],
       ['r'],
       ['r'],
       ['p'],
       ['p'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['r'],
       ['p'],
       ['p'],
       ['p'],
       ['p'],
       ['p'],
       ['p'],
       ['p']], dtype=object)

In [43]:
encoder.fit(labels)

LabelEncoder()

In [44]:
encoder.transform(labels)

C:\Users\admin\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0])

In [55]:
encoder = LabelEncoder()

columns = X.columns

for column in ['manufacturer', 'model', 'trans', 'drv', 'class']:
    
    encoder.fit(X[column])
    encoded = encoder.transform(X[column])
    X[column] = encoded

X

C:\Users\admin\AppData\Local\Temp\ipykernel_9116\1915006126.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[column] = encoded

     manufacturer  model  displ  year  cyl  trans  drv  cty  hwy  class
1               0      1      1     0    0      3    1    7   15      1
2               0      1      1     0    0      8    1   10   15      1
3               0      1      2     1    0      9    1    9   17      1
4               0      1      2     1    0      0    1   10   16      1
5               0      1      7     0    2      3    1    5   12      1
..            ...    ...    ...   ...  ...    ...  ...  ...  ...    ...
230            14     31      2     1    0      7    1    8   14      2
231            14     31      2     1    0      9    1   10   15      2
232            14     31      7     0    2      3    1    5   12      2
233            14     31      7     0    2      8    1    7   12      2
234            14     31     13     1    2      7    1    6   12      2

[220 rows x 10 columns]

In [50]:
X.columns

Index(['manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty',
       'hwy', 'class'],
      dtype='object')

In [52]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
features_ = []
for column in X.columns:
    features_.append(encoder.fit_transform(X[column]))
    labels = encoder.fit_transform(labels)

features=pd.DataFrame(np.array(features_).reshape(-1,10), columns = ['manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty',
       'hwy', 'class'])

In [56]:

encoder = LabelEncoder()

for i in X.columns:
    X[i]=encoder.fit_transform(X[i]) # X['manufacturer']
    
X

C:\Users\admin\AppData\Local\Temp\ipykernel_9116\1493324226.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[i]=encoder.fit_transform(X[i])

     manufacturer  model  displ  year  cyl  trans  drv  cty  hwy  class
1               0      1      1     0    0      3    1    7   15      1
2               0      1      1     0    0      8    1   10   15      1
3               0      1      2     1    0      9    1    9   17      1
4               0      1      2     1    0      0    1   10   16      1
5               0      1      7     0    2      3    1    5   12      1
..            ...    ...    ...   ...  ...    ...  ...  ...  ...    ...
230            14     31      2     1    0      7    1    8   14      2
231            14     31      2     1    0      9    1   10   15      2
232            14     31      7     0    2      3    1    5   12      2
233            14     31      7     0    2      8    1    7   12      2
234            14     31     13     1    2      7    1    6   12      2

[220 rows x 10 columns]

In [57]:
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0])

In [59]:
encoder = LabelEncoder()
labels = encoder.fit_transform(labels) 
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [60]:
from sklearn.tree import DecisionTreeClassifier
dt_clf= DecisionTreeClassifier()

In [63]:
# 정제한 데이터 구간을 5개로 나누고, 평가지표는 정확도를 사용하시오
from sklearn.model_selection import cross_val_score

cross_val_score(dt_clf,features,labels, scoring='accuracy', cv=5)
# labels의 특징 0과 1의 특징을 찾아서 feature속성이 비슷한거 함

array([0.68181818, 0.43181818, 0.54545455, 0.52272727, 0.54545455])

In [75]:
score=cross_val_score(dt_clf,features,labels, scoring='accuracy', cv=5)
np.mean(score)

0.5863636363636364

In [119]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline
card= pd.read_csv('creditcard.csv')
card.head(3)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0

In [80]:
conda install -c conda-forge imbalanced-learn

Collecting package metadata (current_repodata.json): ...working... done
Note: you may need to restart the kernel to use updated packages.

Solving environment: ...working...
Warning: 8 possible package resolutions (only showing differing packages):
  - anaconda/win-64::ca-certificates-2022.3.29-haa95532_1, anaconda/win-64::certifi-2021.10.8-py39haa95532_2, anaconda/win-64::openssl-1.1.1n-h2bbff1b_0
  - anaconda/win-64::ca-certificates-2022.3.29-haa95532_1, anaconda/win-64::openssl-1.1.1n-h2bbff1b_0, defaults/win-64::certifi-2021.10.8-py39haa95532_2
  - anaconda/win-64::ca-certificates-2022.3.29-haa95532_1, anaconda/win-64::certifi-2021.10.8-py39haa95532_2, defaults/win-64::openssl-1.1.1n-h2bbff1b_0
  - anaconda/win-64::ca-certificates-2022.3.29-haa95532_1, defaults/win-64::certifi-2021.10.8-py39haa95532_2, defaults/win-64::openssl-1.1.1n-h2bbff1b_0
  - anaconda/win-64::certifi-2021.10.8-py39haa95532_2, defaults/win-64::ca-certificates-2022.3.29-haa95532_1, defaults/win-64::openssl-1.1.1n-h2bbff1b_0
  - defaults/win-64::ca-certificates-2022.3.29-haa95532_1, defaults/win-64::certifi-2021.10.8-py39haa95532_2, defaults/win-64::openssl-1.1.1n-h2bbff1b_0
  - anaconda/win-64::certifi-2021.10.8-py39haa95532_2, anaconda/win-64::openssl-1.1.1n-h2bbff1b_0, defaults/win-64::ca-certificates-2022.3.29-haa95532_1
  - anaconda/win-64::openssl-1.1.1n-h2bbff1b_0, defaults/win-64::ca-certificates-2022.3.29-haa95532_1, defaults/win-64::certifi-2021.10.8-py39haa95532_2done

## Package Plan ##

  environment location: C:\Users\admin\anaconda3

  added / updated specs:
    - imbalanced-learn


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    imbalanced-learn-0.7.0     |             py_1          97 KB  conda-forge
    ------------------------------------------------------------
                                           Total:          97 KB

The following NEW packages will be INSTALLED:

  imbalanced-learn   conda-forge/noarch::imbalanced-learn-0.7.0-py_1 None



Downloading and Extracting Packages

imbalanced-learn-0.7 | 97 KB     |            |   0%
imbalanced-learn-0.7 | 97 KB     | ########## | 100%
imbalanced-learn-0.7 | 97 KB     | ########## | 100%
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - inbalanced-learn

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

In [81]:
# pip install imbalanced-learn

In [120]:
# time 칼럼삭제 
card.drop('Time', axis=1, inplace=True)

In [84]:
features=X=card.iloc[:, :-1]
labels=y=card.iloc[:,-1]

In [85]:
from sklearn.model_selection import train_test_split

In [121]:
X_train, X_test,y_train, y_test=train_test_split(features, labels, test_size=.3, stratify=labels)
# stratify는 비율에 맞게임

In [90]:
y_train.value_counts()/len(y_train)

0    0.998275
1    0.001725
Name: Class, dtype: float64

In [91]:
from sklearn.linear_model import LogisticRegression

In [92]:
lr_clf= LogisticRegression(max_iter=1000)

In [93]:
lr_clf.fit(X_train, y_train)
lr_pred=lr_clf.predict(X_test)
lr_pred_proba=lr_clf.predict_proba(X_test)[:,1]

In [95]:

from sklearn.metrics import roc_auc_score, confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

def get_clf_eval(y_test, pred=None, pred_proba=None):
    confusion = confusion_matrix( y_test, pred)
    accuracy = accuracy_score(y_test , pred)
    precision = precision_score(y_test , pred)
    recall = recall_score(y_test , pred)
    f1 = f1_score(y_test,pred)
    # ROC-AUC 추가 
    roc_auc = roc_auc_score(y_test, pred_proba)
    print('오차 행렬')
    print(confusion)
    # ROC-AUC print 추가
    print('정확도: {0:.4f}, 정밀도: {1:.4f}, 재현율: {2:.4f},\
    F1: {3:.4f}, AUC:{4:.4f}'.format(accuracy, precision, recall, f1, roc_auc))

In [96]:
get_clf_eval(y_test, lr_pred, lr_pred_proba)

오차 행렬
[[85284    11]
 [   66    82]]
정확도: 0.9991, 정밀도: 0.8817, 재현율: 0.5541,    F1: 0.6805, AUC:0.9653

In [ ]:
TN   FP # TN가 적음 
FN   TP

In [97]:
#3.1

In [98]:
from lightgbm import LGBMClassifier

In [100]:
lgbm_clf= LGBMClassifier(n_estimators=1000, num_leaves=64, n_jobs=-1, boost_from_average=False)
lgbm_clf.fit(X_train, y_train)
preds=lgbm_clf.predict(X_test)
preds_proba=lgbm_clf.predict_proba(X_test)[:,1]

In [101]:
get_clf_eval(y_test, preds, preds_proba)

오차 행렬
[[85291     4]
 [   32   116]]
정확도: 0.9996, 정밀도: 0.9667, 재현율: 0.7838,    F1: 0.8657, AUC:0.9841

In [102]:
## 데이터 정제(스케일링) 후 적용

In [103]:
card['Amount'].describe()

count    284807.000000
mean         88.349619
std         250.120109
min           0.000000
25%           5.600000
50%          22.000000
75%          77.165000
max       25691.160000
Name: Amount, dtype: float64

In [104]:
# 표준화하기 표준정규분포로 만들기

In [108]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
s=scaler.fit_transform(np.array(card['Amount'].values.reshape(-1,1)))
s

array([[ 0.24496426],
       [-0.34247454],
       [ 1.16068593],
       ...,
       [-0.0818393 ],
       [-0.31324853],
       [ 0.51435531]])

In [111]:
card['Amount']=s

In [113]:
card

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,0.244964,0
1,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,-0.342475,0
2,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,1.160686,0
3,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,0.140534,0
4,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,-0.073403,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,4.356170,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,-0.350151,0
284803,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,-0.975926,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,-0.254117,0
284804,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,-0.484782,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,-0.081839,0
284805,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,-0.399126,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,-0.313249,0
284806,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,-0.915427,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,0.514355,0

In [114]:
features=X=card.iloc[:, :-1]
labels=y=card.iloc[:,-1]

In [115]:
lr_clf= LogisticRegression(max_iter=1000)
lr_clf.fit(X_train, y_train)
lr_pred=lr_clf.predict(X_test)
lr_pred_proba=lr_clf.predict_proba(X_test)[:,1]
get_clf_eval(y_test, lr_pred, lr_pred_proba)

오차 행렬
[[85284    11]
 [   66    82]]
정확도: 0.9991, 정밀도: 0.8817, 재현율: 0.5541,    F1: 0.6805, AUC:0.9653

In [116]:
lgbm_clf= LGBMClassifier(n_estimators=1000, num_leaves=64, n_jobs=-1, boost_from_average=False)
lgbm_clf.fit(X_train, y_train)
preds=lgbm_clf.predict(X_test)
preds_proba=lgbm_clf.predict_proba(X_test)[:,1]
get_clf_eval(y_test, preds, preds_proba)

오차 행렬
[[85291     4]
 [   32   116]]
정확도: 0.9996, 정밀도: 0.9667, 재현율: 0.7838,    F1: 0.8657, AUC:0.9841

In [118]:
# 데이터 정제(로그변환)후 전환

In [126]:
card= pd.read_csv('creditcard.csv')
card.drop('Time', axis=1, inplace=True)

In [127]:
card['Amount']=np.log1p(card['Amount']) # 로그를 사용하는 이유? 숫자가 너무 커서 사용
card

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,5.014760,0
1,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,1.305626,0
2,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,5.939276,0
3,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,4.824306,0
4,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,4.262539,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,4.356170,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.570980,0
284803,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,-0.975926,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,3.249987,0
284804,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,-0.484782,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,4.232366,0
284805,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,-0.399126,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,2.397895,0
284806,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,-0.915427,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,5.384495,0

In [128]:
features=X=card.iloc[:, :-1]
labels=y=card.iloc[:,-1]
X_train, X_test,y_train, y_test=train_test_split(features, labels, test_size=.3, stratify=labels)

In [129]:
lr_clf= LogisticRegression(max_iter=1000)
lr_clf.fit(X_train, y_train)
lr_pred=lr_clf.predict(X_test)
lr_pred_proba=lr_clf.predict_proba(X_test)[:,1]
print(get_clf_eval(y_test, lr_pred, lr_pred_proba))
print()
lgbm_clf= LGBMClassifier(n_estimators=1000, num_leaves=64, n_jobs=-1, boost_from_average=False)
lgbm_clf.fit(X_train, y_train)
preds=lgbm_clf.predict(X_test)
preds_proba=lgbm_clf.predict_proba(X_test)[:,1]
print(get_clf_eval(y_test, preds, preds_proba))

오차 행렬
[[85283    12]
 [   58    90]]
정확도: 0.9992, 정밀도: 0.8824, 재현율: 0.6081,    F1: 0.7200, AUC:0.9697
None

오차 행렬
[[85288     7]
 [   33   115]]
정확도: 0.9995, 정밀도: 0.9426, 재현율: 0.7770,    F1: 0.8519, AUC:0.9741
None

In [130]:
IQR

3/4 +1.5IQR
1/4 +1.5IQR

SyntaxError: invalid syntax (1631740005.py, line 3)

In [132]:
fraud =card[card['Class']==1]
fraud

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
541,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,-2.772272,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.000000,1
623,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,-0.838587,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,6.272877,1
4920,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,-0.238253,-1.525412,...,-0.294166,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,5.484506,1
6108,-4.397974,1.358367,-2.592844,2.679787,-1.128131,-1.706536,-3.496197,-0.248778,-0.247768,-4.801637,...,0.573574,0.176968,-0.436207,-0.053502,0.252405,-0.657488,-0.827136,0.849573,4.094345,1
6329,1.234235,3.019740,-4.304597,4.732795,3.624201,-1.357746,1.713445,-0.496358,-1.282858,-2.447469,...,-0.379068,-0.704181,-0.656805,-1.632653,1.488901,0.566797,-0.010016,0.146793,0.693147,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,-5.587794,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,5.968708,1
280143,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,-3.232153,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.565314,1
280149,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,-3.463891,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,4.368054,1
281144,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,-5.245984,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,5.505332,1
281674,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,-0.888722,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,3.773450,1

In [134]:
fraud['V14']

541      -4.289254
623      -1.692029
4920     -1.470102
6108     -6.771097
6329     -6.079337
            ...
279863   -6.665177
280143   -5.210141
280149   -4.057162
281144   -6.416628
281674   -1.948883
Name: V14, Length: 492, dtype: float64

In [135]:
#3/4 +1.5IQR
#1/4 +1.5IQR

pct75 =fraud['V14'].quantile(0.75)
pct25 =fraud['V14'].quantile(0.25)

In [136]:
IQR=pct75-pct25

In [137]:
IQR*1.5

8.114853173228282

In [140]:
upper=pct75+1.5*IQR
lower=pct25-1.5*IQR

In [145]:
fraud[(fraud['V14']<upper) |(fraud['V14']>lower)]

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
541,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,-2.770089,-2.772272,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.000000,1
623,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,-0.270953,-0.838587,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,6.272877,1
4920,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,-0.238253,-1.525412,...,-0.294166,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,5.484506,1
6108,-4.397974,1.358367,-2.592844,2.679787,-1.128131,-1.706536,-3.496197,-0.248778,-0.247768,-4.801637,...,0.573574,0.176968,-0.436207,-0.053502,0.252405,-0.657488,-0.827136,0.849573,4.094345,1
6329,1.234235,3.019740,-4.304597,4.732795,3.624201,-1.357746,1.713445,-0.496358,-1.282858,-2.447469,...,-0.379068,-0.704181,-0.656805,-1.632653,1.488901,0.566797,-0.010016,0.146793,0.693147,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279863,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,-5.587794,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,5.968708,1
280143,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,-3.232153,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.565314,1
280149,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,-3.463891,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,4.368054,1
281144,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,-5.245984,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,5.505332,1
281674,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,-0.888722,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,3.773450,1

In [151]:
pct75 =fraud['V14'].quantile(0.75)
pct25 =fraud['V14'].quantile(0.25)
IQR=pct75-pct25
upper=pct75+1.5*IQR
lower=pct25-1.5*IQR
fraud['V14'][(fraud['V14']>=upper) |(fraud['V14']<=lower)]

8296   -19.214325
8615   -18.822087
9035   -18.493773
9252   -18.049998
Name: V14, dtype: float64

In [149]:
pct25 = np.percentile(fraud.V14, 25)
pct75 = np.percentile(fraud.V14, 75)

IQR = pct75 - pct25

upper_out = pct75 + 1.5 * IQR
under_out = pct25 - 1.5 * IQR

cond1 = fraud['V14'] >= upper_out
cond2 = fraud['V14'] <= under_out
fraud.V14[cond1 | cond2]

8296   -19.214325
8615   -18.822087
9035   -18.493773
9252   -18.049998
Name: V14, dtype: float64

In [153]:
outlier=fraud['V14'][(fraud['V14']>=upper) |(fraud['V14']<=lower)]
outlier.index

Int64Index([8296, 8615, 9035, 9252], dtype='int64')

In [166]:
card.drop(labels=[8296, 8615, 9035, 9252], axis=0,inplace=True)

KeyError: '[8296, 8615, 9035, 9252] not found in axis'

In [169]:
outlier.index
card.drop(outlier.index, axis=0,inplace=True)

Int64Index([8296, 8615, 9035, 9252], dtype='int64')

In [165]:
# 데이터 프레임의 차집합은 어려움

In [167]:
card-fraud[['V14']][(fraud['V14']>=upper) |(fraud['V14']<=lower)] # 이건 안됨

,Amount,Class,V1,V10,V11,V12,V13,V14,V15,V16,...,V26,V27,V28,V3,V4,V5,V6,V7,V8,V9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284803,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284804,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284805,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
284806,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [168]:
card

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,5.014760,0
1,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,1.305626,0
2,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,5.939276,0
3,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,4.824306,0
4,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,4.262539,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,4.356170,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.570980,0
284803,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,-0.975926,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,3.249987,0
284804,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,-0.484782,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,4.232366,0
284805,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,-0.399126,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,2.397895,0
284806,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,-0.915427,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,5.384495,0

In [170]:
features=X=card.iloc[:, :-1]
labels=y=card.iloc[:,-1]
X_train, X_test,y_train, y_test=train_test_split(features, labels, test_size=.3, stratify=labels)

In [171]:
lr_clf= LogisticRegression(max_iter=1000)
lr_clf.fit(X_train, y_train)
lr_pred=lr_clf.predict(X_test)
lr_pred_proba=lr_clf.predict_proba(X_test)[:,1]
print(get_clf_eval(y_test, lr_pred, lr_pred_proba))
print()
lgbm_clf= LGBMClassifier(n_estimators=1000, num_leaves=64, n_jobs=-1, boost_from_average=False)
lgbm_clf.fit(X_train, y_train)
preds=lgbm_clf.predict(X_test)
preds_proba=lgbm_clf.predict_proba(X_test)[:,1]
print(get_clf_eval(y_test, preds, preds_proba))

오차 행렬
[[85284    11]
 [   57    89]]
정확도: 0.9992, 정밀도: 0.8900, 재현율: 0.6096,    F1: 0.7236, AUC:0.9716
None

오차 행렬
[[85289     6]
 [   29   117]]
정확도: 0.9996, 정밀도: 0.9512, 재현율: 0.8014,    F1: 0.8699, AUC:0.9771
None

In [172]:
# Smote로 오버샘플링

In [178]:
card= pd.read_csv('creditcard.csv')
card.drop('Time', axis=1, inplace=True)

features=X=card.iloc[:, :-1]
labels=y=card.iloc[:,-1]
X_train, X_test,y_train, y_test=train_test_split(features, labels, test_size=.3, stratify=labels)

In [173]:
from imblearn.over_sampling import SMOTE

In [179]:
smote=SMOTE(random_state=0)

In [180]:
X_train_over, y_train_over =smote.fit_resample(X_train, y_train)

In [181]:
X_train_over.shape

(398040, 29)

In [182]:
y_train_over.value_counts()

0    199020
1    199020
Name: Class, dtype: int64

In [184]:
lr_clf= LogisticRegression(max_iter=1000)
lr_clf.fit(X_train_over, y_train_over)
lr_pred=lr_clf.predict(X_test)
lr_pred_proba=lr_clf.predict_proba(X_test)[:,1]
print(get_clf_eval(y_test, lr_pred, lr_pred_proba))
print()
lgbm_clf= LGBMClassifier(n_estimators=1000, num_leaves=64, n_jobs=-1, boost_from_average=False)
lgbm_clf.fit(X_train_over, y_train_over)
preds=lgbm_clf.predict(X_test)
preds_proba=lgbm_clf.predict_proba(X_test)[:,1]
print(get_clf_eval(y_test, preds, preds_proba))

오차 행렬
[[83723  1572]
 [   18   130]]
정확도: 0.9814, 정밀도: 0.0764, 재현율: 0.8784,    F1: 0.1405, AUC:0.9654
None

오차 행렬
[[42771 42524]
 [   17   131]]
정확도: 0.5021, 정밀도: 0.0031, 재현율: 0.8851,    F1: 0.0061, AUC:0.6933
None

In [185]:

import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score 


cancer = load_breast_cancer()
type(cancer)

# 데이터 처리
X_data = cancer.data

y_label = cancer.target

X_train , X_test , y_train , y_test = train_test_split(X_data , y_label , test_size=0.2 , random_state=0) 

knn_clf  = KNeighborsClassifier(n_neighbors=4)
rf_clf = RandomForestClassifier(n_estimators=100, random_state=0)
dt_clf = DecisionTreeClassifier()
ada_clf = AdaBoostClassifier(n_estimators=100) 


# 개별 모델들을 학습. 
knn_clf.fit(X_train, y_train)
rf_clf.fit(X_train , y_train)
dt_clf.fit(X_train , y_train)
ada_clf.fit(X_train, y_train)

# 학습된 개별 모델들이 각자 반환하는 예측 데이터 셋을 생성하고 개별 모델의 정확도 측정. 
knn_pred = knn_clf.predict(X_test)
rf_pred = rf_clf.predict(X_test)
dt_pred = dt_clf.predict(X_test)
ada_pred = ada_clf.predict(X_test) 


print('KNN 정확도: {0:.4f}'.format(accuracy_score(y_test, knn_pred)))
print('랜덤 포레스트 정확도: {0:.4f}'.format(accuracy_score(y_test, rf_pred)))
print('결정 트리 정확도: {0:.4f}'.format(accuracy_score(y_test, dt_pred)))
print('에이다부스트 정확도: {0:.4f} :'.format(accuracy_score(y_test, ada_pred)))

KNN 정확도: 0.9211
랜덤 포레스트 정확도: 0.9649
결정 트리 정확도: 0.9123
에이다부스트 정확도: 0.9561 :

In [186]:
pred = np.array([knn_pred, rf_pred, dt_pred, ada_pred]) 
pred = pred.T
print(pred.shape) 
# 앞에 예측치들에대해 새로운 large X를 만듬

# 최종 Stacking 모델을 위한 Classifier생성. 
lr_final = LogisticRegression(C=10) 
lr_final.fit(pred, y_test)
final = lr_final.predict(pred) 

accuracy_score(y_test, final)

(114, 4)

0.9736842105263158

In [187]:

       [0, 0, 0, 0],  0
       [1, 1, 1, 1],  1
       [1, 1, 1, 1],  1
       [0, 1, 0, 1],  1
       [1, 1, 1, 1],  1

([1, 1, 1, 1], 1)

In [188]:
오버 샘플링이 언더 샘플링보다 유리하다.
오버 샘플링은 학습데이터 세트에서만 행해야 한다.
로그변환은 데이터 분포도가 심하게 왜곡되어 있을 경우 적용하는 중요기법 중 하나이다.

SyntaxError: invalid syntax (4089438616.py, line 1)

In [ ]:
import pandas as pd
import numpy as np 
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

0      N
1      C
2      N
3      C
4      N
      ..
886    N
887    B
888    N
889    C
890    N
Name: Cabin, Length: 891, dtype: object

In [250]:



titanic=pd.read_csv("titanic_train.csv")

#titanic.isna().sum()

titanic.Age=titanic.Age.fillna(np.mean(titanic['Age']))

titanic['Cabin'].fillna('N',inplace=True)
titanic['Embarked'].fillna('N',inplace=True)

titanic['Cabin']=titanic['Cabin'].str[:1]

In [251]:

encoder= LabelEncoder()
#titanic['Cabin']=encoder.fit_transform(titanic['Cabin']).tolist()
#titanic['Sex']=encoder.fit_transform(titanic['Sex']).tolist()
#titanic['Embarked']=encoder.fit_transform(titanic['Embarked']).tolist()
#titanic

for i in ['Cabin', 'Sex', 'Embarked']:
    
    titanic[i]=encoder.fit_transform(titanic[i])
titanic

titanic=titanic.drop(['PassengerId', 'Name', 'Ticket'], axis=1)
titanic

features = X = titanic.iloc[:, 1:] # 데이터프레임 
labels = y = titanic.iloc[:, 0] 

X_train,X_test,y_train,y_test,=train_test_split(features, labels, test_size=0.2, random_state=11)

In [252]:


dt_clf=DecisionTreeClassifier()
rf_clf=RandomForestClassifier()
lr_clf=LogisticRegression()

dt_clf.fit(X_train, y_train)
rf_clf.fit(X_train, y_train)
lr_clf.fit(X_train, y_train)

dt_pred = dt_clf.predict(X_test)
rf_pred = rf_clf.predict(X_test)
lr_pred = lr_clf.predict(X_test)

print("정확도:" ,accuracy_score(y_test, dt_pred).round(4))
print("정확도:" ,accuracy_score(y_test, rf_pred).round(4))
print("정확도:" ,accuracy_score(y_test, lr_pred).round(4))

pred = np.array([dt_pred, rf_pred, lr_pred]) 

pred = pred.T

lr_final = LogisticRegression(C=10) 
lr_final.fit(pred, y_test)
final = lr_final.predict(pred) 
accuracy_score(y_test, final)

정확도: 0.8156
정확도: 0.8659
정확도: 0.8492

0.888268156424581

In [ ]:
0. 불러 오세요.

import pandas as pd

import numpy as np 

from sklearn.metrics import accuracy_score

from sklearn.preprocessing import LabelEncoder

from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import RandomForestClassifier

from sklearn.linear_model import LogisticRegression



----------------------------------------------------------------



1.  타이타닉 파일을 불러온 후 titanic.Age의 결측치는 평균으로 채우고 , titanic['Cabin'],titanic['Embarked']의 결측치는

'N'으로 채우고, titanic['Cabin']의 첫 글자만 불러오세요.  





titanic=pd.read_csv("titanic_train.csv")



#titanic.isna().sum()



titanic.Age=titanic.Age.fillna(np.mean(titanic['Age']))



titanic['Cabin'].fillna('N',inplace=True)

titanic['Embarked'].fillna('N',inplace=True)



titanic['Cabin']=titanic['Cabin'].str[:1]



------------------------------------------------------



2. 타이타닉의 'Cabin', 'Sex', 'Embarked'를 라벨 인코딩 한 후 'PassengerId', 'Name', 'Ticket' 열은 버리고,

 labels= Survived로 하고 features는 나머지 전부 열을 하고 트레이닝 세트와 테스트 세트(0.2)로 분리해주세요.

(단,  random_state=11 입니다.) 



encoder= LabelEncoder()

#titanic['Cabin']=encoder.fit_transform(titanic['Cabin']).tolist()

#titanic['Sex']=encoder.fit_transform(titanic['Sex']).tolist()

#titanic['Embarked']=encoder.fit_transform(titanic['Embarked']).tolist()

#titanic



for i in ['Cabin', 'Sex', 'Embarked']:

    

    titanic[i]=encoder.fit_transform(titanic[i])



titanic=titanic.drop(['PassengerId', 'Name', 'Ticket'], axis=1)



features = X = titanic.iloc[:, 1:]

labels = y = titanic.iloc[:, 0] 



X_train,X_test,y_train,y_test,=train_test_split(features, labels, test_size=0.2, random_state=11) 



-------------------------------------------------------



dt_clf=DecisionTreeClassifier()

rf_clf=RandomForestClassifier()

lr_clf=LogisticRegression()



3. 위의 알고리즘을 학습시킨 후 모아서 스태킹 하세요. 

 
dt_clf.fit(X_train, y_train)
rf_clf.fit(X_train, y_train)
lr_clf.fit(X_train, y_train)

dt_pred = dt_clf.predict(X_test)
rf_pred = rf_clf.predict(X_test)
lr_pred = lr_clf.predict(X_test)

print("정확도:" ,accuracy_score(y_test, dt_pred).round(4))
print("정확도:" ,accuracy_score(y_test, rf_pred).round(4))
print("정확도:" ,accuracy_score(y_test, lr_pred).round(4))

pred = np.array([dt_pred, rf_pred, lr_pred]) 

pred = pred.T

lr_final = LogisticRegression(C=10) 
lr_final.fit(pred, y_test)
final = lr_final.predict(pred) 
accuracy_score(y_test, final)